[constants]
runtime = '@runtime@'

[binaries]
cpp = '@clang@/bin/clang++'
ar = '@llvm@/bin/llvm-ar'
strip = '@llvm@/bin/llvm-strip'

[host_machine]
system = 'plan9'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
# cc9 lacks _SC_OPEN_MAX and does not implement utimensat's full flags/time semantics.
has_function_sysconf = false
has_function_utimensat = false
# cc9 statvfs reports ENOSYS.
has_function_statvfs = false

[built-in options]
cpp_args = ['--target=x86_64-unknown-none', '-D__plan9__', '-fno-pic', '-ffunction-sections', '-fdata-sections', '-nostdinc++', '-nostdlib', '-femulated-tls', '-isystem', runtime / 'sysinc/cxxv1', '-isystem', runtime / 'sysinc/cc9', '-D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE', '-D_LIBCPP_HAS_CLOCK_GETTIME']
# Select Clang's ELF linker driver; all startup code and libraries come from cc9.
cpp_link_args = ['--target=x86_64-unknown-linux-gnu', '-nostdlib', '--ld-path=@lld@/bin/ld.lld', '-static', '-Wl,--gc-sections', '-Wl,-T,' + runtime / 'plan9.ld', runtime / 'crt0.o', runtime / 'libcc9cxx.a', runtime / 'libcc9m.a']
default_library = 'static'
b_staticpic = false
b_pch = false
