set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER @clang@/bin/clang)
set(CMAKE_CXX_COMPILER @clang@/bin/clang++)
set(CMAKE_C_COMPILER_TARGET x86_64-unknown-none)
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-none)
set(CMAKE_C_FLAGS_INIT "-D__plan9__ -fno-pic -femulated-tls -ffunction-sections -fdata-sections -isystem @runtime@/sysinc/cc9")
set(CMAKE_CXX_FLAGS_INIT "-nostdinc++ -isystem @runtime@/sysinc/cxxv1 -D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE -D_LIBCPP_HAS_CLOCK_GETTIME ${CMAKE_C_FLAGS_INIT}")
set(CMAKE_AR @llvm@/bin/llvm-ar)
set(CMAKE_RANLIB @llvm@/bin/llvm-ranlib)
set(CMAKE_LINKER @lld@/bin/ld.lld)
# Link feature checks against the target runtime, without invoking a host driver.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static --gc-sections -T @runtime@/plan9.ld")
set(CMAKE_C_STANDARD_LIBRARIES "--start-group @runtime@/libcc9cxx.a @runtime@/libcc9m.a --end-group")
set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_C_STANDARD_LIBRARIES}")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_C_LINK_EXECUTABLE}")
set(CMAKE_FIND_ROOT_PATH @prefix@ @runtime@/sysinc/cc9)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
